### ISSUE TITLE
mobile: securely store database key

### ISSUE THREAD

**Issue by skerkour** [skerkour/bloom-legacy#14]
# Tasks

## Android

* [ ] https://developer.android.com/training/articles/keystore

## Linux

* [x] https://askubuntu.com/questions/1700/what-is-the-keyring-or-keychain

## macOS

* [x] https://developer.apple.com/documentation/security/keychain_services

## iOS

* [ ] https://developer.apple.com/documentation/security/keychain_services
